# Postmodeling Configuration File
  
  project_path: 'triage_output/output/' # Project path defined in triage with matrices and models
  audition_output_path: 'results_model_group_ids.json' # Audition output path 
  model_group_id: # List of model_id's [optional if a audition_output_path is given]
        - 19
        - 43
        - 55

  thresholds: # Thresholds for defining positive predictions 
        rank_abs: [10, 20]
        rank_pct: [10, 25, 50]

  baseline_query: | # SQL query for defining a baseline for comparison in plots. It needs a metric and parameter
      SELECT g.model_group_id,
             m.model_id,
             EXTRACT('YEAR' FROM m.evaluation_end_time) AS as_of_date_year,
             m.metric,
             m.parameter,
             m.value,
             m.num_labeled_examples,
             m.num_labeled_above_threshold,
             m.num_positive_labels
       FROM test_results.evaluations m
       LEFT JOIN triage_metadata.models g
       USING(model_id)
       WHERE g.model_group_id IN (1, 2, 3)
             AND metric = 'precision@'
             AND parameter = '10.0_pct'

  max_depth_error_tree: 5 # For error trees, how depth the decision trees should go?
  n_features_plots: 10 # Number of features for importances
  figsize: [12, 12] # Default size for plots
  fontsize: 20 # Default fontsize for plots
