version: 1

formatters:
  simple:
    format: '%(asctime)s - %(message)s'
    datefmt: '%d/%m/%Y %I:%M'
  colored_console:
    (): 'coloredlogs.ColoredFormatter'
    format: '%(asctime)s :: %(message)s'
    datefmt: '%d/%m/%Y %I:%M'
  rich:
    format: '%(name)-30s  %(asctime)s %(levelname)10s %(process)6d  %(filename)-24s  %(lineno)4d: %(message)s'
    datefmt: '%d/%m/%Y %I:%M:%S %p'

handlers:
  console:
    class: logging.StreamHandler
    formatter: colored_console
    stream: ext://sys.stdout

loggers:
  triage:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: WARNING
  handlers: [console]
