version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  rich:
    format: '%(name)-30s  %(asctime)s %(levelname)10s %(process)6d  %(filename)-24s  %(lineno)4d: %(message)s'
    datefmt: '%d/%m/%Y %I:%M:%S %p'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

loggers:
  triage:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: WARNING
  handlers: [console]
