name: Build Docs and Serve to Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  docs:
    name: Build Docs and Serve to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv sync --extra docs
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish docs
        run: uv run mkdocs gh-deploy -f "$(pwd)/docs/mkdocs.yml"
