name: Build Docs and Serve to Github Pages

on:
  push:
    tags:
      - v*
  
jobs:
  docs:
    name: Build Docs and Serve to Github Pages
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install --upgrade pip && pip install -r requirement/dev.txt
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy -f "$(pwd)/docs/mkdocs.yml"
