name: Python package

on:
  push:
    tags:
     - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        uv pip install --system 'tox>=4.14,<5'
        uv pip install --system flake8 pytest
    - name: Test with tox
      run: |
        tox
